# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Palette
# C9A7EB
# 8D72E1
# FFD372 - Yellow
# 80489C - Purple

# Change the default prompt format
format = """\
[â•­â”€](238)\
[î‚¶](#80489C)\
${env_var.STARSHIP_DISTRO}\
$shell\
[î‚°](fg:#80489C bg:#FFD372)\
$username\
[î‚°](fg:#FFD372 bg:#23967F)\
$directory\
[î‚°](fg:#23967F bg:#004346)\
$git_branch$git_status\
[î‚°](fg:#004346 bg:#8267BE)\
$golang\
$python\
$docker_context\
[î‚°](fg:#8267BE)\
$line_break\
[â”‚](238)\
$line_break\
[â•°â”€â”€](238)$character\
"""

# Change the default prompt characters
[character]
success_symbol = "[ï•“](238)"
error_symbol = "[ï•“](238)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value]($style)'
style = "bg:#80489C"  # removed space between distro and rest for pwsh
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "fg:#3D3C42 bg:#FFD372"
style_root = "fg:#3D3C42 bg:#FFD372"
format = "[ ï€‡ $user ]($style)"
disabled = false  # disable in powershell
show_always = true

[shell]
format = '[$indicator]($style)'
fish_indicator = 'FISH '
bash_indicator = 'BASH '
powershell_indicator = 'PWSH '
unknown_indicator = 'SH?? '
style = 'bg:#80489C'
disabled = false

[directory]
truncation_length = 1
truncation_symbol = "â€¦/"
style = "bg:#23967F"
home_symbol = "~"
# read_only_style = "197"
# read_only = " ï€£ "
format = "[ î—¿ $path ]($style)"

[git_branch]
symbol = "îœ¥"
format = "[ $symbol $branch ]($style)"
truncation_length = 4
truncation_symbol = "â€¦/"
style = "bg:#004346"

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "bg:#004346"
untracked = "U"
ahead = "â†‘"
behind = "â†“"
diverged = "âš¡"
renamed = "âœ"
deleted = "âœ–"
staged = "+"
conflicted = "!"

# conflicted = "ğŸ³"
# up_to_date = "ï† "
# untracked = "ï”© "
# ahead = "â‡¡${count}"
# diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
# behind = "â‡£${count}"
# stashed = "ï£– "
# modified = "ï„ "
# staged = '[++\($count\)](green)'
# renamed = "ïª¶ "
# deleted = "ï€” "

# Configure Programming Languages and Environments
[aws]
format = '[$symbol$region]($style) '
style = 'bold blue'
symbol = 'ïƒ‚'

[aws.region_aliases]
ap-southeast-2 = 'au'
ap-south-1 = 'in-mumbai'
us-east-1 = 'va'

[golang]
symbol = "î˜§ "
style = "bg:#8267BE"
format = '[ $symbol($version) ]($style)'

[terraform]
format = "via [ï„µ terraform $version]($style) ï¥‚ [$workspace]($style) "

[docker_context]
format = "[ïŒˆ $context ]($style)"
style = "bg:#8267BE"
only_with_files	= true
detect_extensions = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']

[python]
symbol = "ï Ÿ "
style = "bg:#8267BE"
format = '[ $symbol($version) ]($style)'
python_binary = "python3"